apiVersion: v1
kind: Service
metadata:
  name: hello-flask-svc
spec:
  type: NodePort
  selector:
    app: hello-flask
  ports:
    - protocol: TCP
      port: 4600
      targetPort: 4600
      nodePort: 32666

